// <auto-generated />
namespace CodeExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditTaskLederBoard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTaskLederBoard));
        
        string IMigrationMetadata.Id
        {
            get { return "201812280711237_Edit-Task-LederBoard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
